
package servidor.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicioUsuarios", targetNamespace = "http://publicar.servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServicioUsuarios {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.servidor/ServicioUsuarios/validarTokenRequest", output = "http://publicar.servidor/ServicioUsuarios/validarTokenResponse")
    public boolean validarToken(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.servidor/ServicioUsuarios/tipoUsuarioRequest", output = "http://publicar.servidor/ServicioUsuarios/tipoUsuarioResponse")
    public String tipoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
