
package servidor.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.AnyTypeArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicioOfertas", targetNamespace = "http://publicar.servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    servidor.publicar.ObjectFactory.class
})
public interface ServicioOfertas {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.AnyTypeArray
     * @throws KeywordExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.servidor/ServicioOfertas/obtenerKeywordsRequest", output = "http://publicar.servidor/ServicioOfertas/obtenerKeywordsResponse", fault = {
        @FaultAction(className = KeywordExisteException_Exception.class, value = "http://publicar.servidor/ServicioOfertas/obtenerKeywords/Fault/KeywordExisteException")
    })
    public AnyTypeArray obtenerKeywords()
        throws KeywordExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns servidor.publicar.DtPublicacionArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.servidor/ServicioOfertas/obtenerPublicacionesRequest", output = "http://publicar.servidor/ServicioOfertas/obtenerPublicacionesResponse")
    public DtPublicacionArray obtenerPublicaciones();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.publicar.DtPublicacionArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.servidor/ServicioOfertas/obtenerPublicacionesPorBusquedaRequest", output = "http://publicar.servidor/ServicioOfertas/obtenerPublicacionesPorBusquedaResponse")
    public DtPublicacionArray obtenerPublicacionesPorBusqueda(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
